// <auto-generated />
using System;
using AxisUtah.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxisUtah.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815164148_AddingUserIdToPropety")]
    partial class AddingUserIdToPropety
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AxisUtah.Api.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnparsedAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("City", "PostalCode");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<int?>("BrokerageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentId");

                    b.HasIndex("Email");

                    b.HasIndex("BrokerageId", "IsActive");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.AppLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex("EventType");

                    b.HasIndex("Level", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("AppLogEntries");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Brokerage", b =>
                {
                    b.Property<int>("BrokerageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrokerageId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrokerageId");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.HasIndex("City", "IsActive");

                    b.ToTable("Brokerages");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyListingKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PropertyListingKey", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Property", b =>
                {
                    b.Property<int>("ListingKey")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BathroomsTotal")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int?>("BedroomsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("BrokerageId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildingAreaTotal")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBrokerageListing")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("ListAgentFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListOfficeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ListingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("ModificationTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardStatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StateOrProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StructureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnparsedAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ListingKey");

                    b.HasIndex("AddressId");

                    b.HasIndex("ListingKey");

                    b.HasIndex("ModificationTimestamp")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("AgentId", "StandardStatus");

                    b.HasIndex("BrokerageId", "StandardStatus");

                    b.HasIndex("City", "StandardStatus");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.PropertyHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<int>("ListingKey")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc")
                        .IsDescending();

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ListingKey");

                    b.HasIndex("ListingKey", "ChangedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("PropertyHistories");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.PropertyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingKey")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListingKey", "Order");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Expires");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "Expires")
                        .IsDescending(false, true);

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.SyncCheckpoint", b =>
                {
                    b.Property<string>("FeedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModificationTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRunCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FeedName");

                    b.ToTable("SyncCheckpoints");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Email", "IsActive");

                    b.HasIndex("IsActive", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Agent", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.Brokerage", "Brokerage")
                        .WithMany()
                        .HasForeignKey("BrokerageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brokerage");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Lead", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyListingKey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Property", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AxisUtah.Api.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AxisUtah.Api.Models.Brokerage", "Brokerage")
                        .WithMany()
                        .HasForeignKey("BrokerageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AxisUtah.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Address");

                    b.Navigation("Agent");

                    b.Navigation("Brokerage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.PropertyHistory", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("ListingKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.PropertyMedia", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.Property", "Property")
                        .WithMany("Media")
                        .HasForeignKey("ListingKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.UserInfo", b =>
                {
                    b.HasOne("AxisUtah.Api.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("AxisUtah.Api.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.Property", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("AxisUtah.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
