global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using AxisUtah.Api.Models;
global using AxisUtah.Api.Data;
global using System.Text.Json.Serialization;
global using AxisUtah.Api.Dtos;
global using AxisUtah.Api.Mappings;
global using AxisUtah.Api.Services;